spring:
  application:
    name: app-gateway

  cloud:
    gateway:
      routes:
      - id: audit
        uri: ${AUDIT_URI:http://localhost:7001}
        predicates:
          - Path=/audit/**
        filters:
          - JWTAuthFilter


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://localhost:8443/realms/master

server:
  port: 5003