spring:
  application:
    name: app-gateway

  cloud:
    gateway:
      routes:
      - id: audit
        uri: ${AUDIT_URI:http://localhost:7001}
        predicates:
          - Path=/audit/**
        filters:
          - JWTAuthFilter

